spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      pool-name: polardb-pool
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 9002
  shutdown: graceful
  tomcat:
    accept-count: 100
    connection-timeout: 5s
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10