apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-app
  labels:
    app: catalog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-app
  template:
    metadata:
      labels:
        app: catalog-app
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: catalog-app
          image: chungha/catalog-service:0.0.1-SNAPSHOT
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polardb-catalog-postgresql:5432/polardb_catalog
          resources:
            requests:
              memory: "1000Mi"
              cpu: "2"
            limits:
              memory: "1000Mi"